server:
  port: 20000
spring:
  application:
    name: gulimall-auth-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.182.130:8848
  redis:
    host: 192.168.182.130
    port: 6379
  session:
    store-type: redis

  #开发环境设置false
  thymeleaf:
    cache: false

