spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.182.130:8848
    alicloud:
      access-key: LTAI5tJVNgwJZuCpqwAgwZxk
      secret-key: xSj9SCuMOY7HLMzdfhHwuzg3bu0hxS
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-merchen
      sanwang:
        sms:
          appcode: 78cbf06287684192be55c8d45e36d74d

application:
    name: gulimall-third-party
server:
  port: 30000

