spring:
  rabbitmq:
    host: 192.168.182.130
    port: 5672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #开启手动确认ack模式
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.182.130:3306/gulimall_wms?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.182.130:8848
  application:
    name: gulimall-ware
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  #自增主键
server:
  port:  11000
#logging:
#  level:
#   com.merchen.gulimall: debug

